" 1. VUNDLE PLUGIN MANAGER CONFIGURATION
" ============================================================================
set nocompatible              " Be iMproved, required
filetype off                  " Required for Vundle initialization

" Set the runtime path to include Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')

" Let Vundle manage Vundle (Required)
Plugin 'VundleVim/Vundle.vim'

" Active Plugins
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } } " Core FZF binary
Plugin 'junegunn/fzf.vim'                             " FZF Vim wrapper plugin
Plugin 'easymotion/vim-easymotion'
Plugin 'tpope/vim-rails'
Plugin 'scrooloose/nerdcommenter'
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'jiangmiao/auto-pairs'
Plugin 'sainnhe/everforest'
Plugin 'voldikss/vim-floaterm'
Plugin 'tpope/vim-surround'
Plugin 'mattn/emmet-vim'
Plugin 'Yggdroot/indentLine'

call vundle#end()            " Required
filetype plugin indent on    " Enable loading indent files for specific file types

" ============================================================================
" 2. GENERAL SETTINGS (UI & Behavior)
" ============================================================================
syntax on                    " Enable syntax highlighting
set number                   " Show absolute line number on current line
set rnu                      " Use relative line numbers for easy jumping
set ruler                    " Always show the cursor's current position
set laststatus=2             " Always show the status line
set tw=120                   " Set text-width to 120 characters
set wrap                     " Wrap long lines visually

" Status line
set statusline=%F\                    " FilePath
set statusline+=%m\                   " Modified flag [+]
set statusline+=%=                    " Alignment separator ()switch to right side)
set statusline+=%{FugitiveStatusline()}  " Git branch (provided by vim-fugituve)
set statusline+=\ [%Y]                   " File type (e.g. [ruby], [html])
set statusline+=\ %l:%c\


"Search Settings
set ignorecase               " Ignore case when searching
set smartcase                " ...unless search contains an uppercase letter
set incsearch                " Show search matches dynamically as you type
set magic                    " Turn on 'magic' for regular expressions
set showmatch                " Briefly flash matching brackets

" Tab & Indentation Settings
set tabstop=4                " Number of visual spaces per TAB
set shiftwidth=4             " Number of spaces to use for autoindent
set expandtab                " Convert TABs to spaces
set ai                       " Copy indent from current line when starting a new one

" History & Performance
set history=500              " Remember up to 500 commands
set wildmenu                 " Visual autocomplete menu for command mode

" Theme & GUI Settings
if has('gui_running')
    set background=light

    " --- FORCE FULL SCREEN ON STARTUP ---
    set lines=999 columns=999
    set fullscreen
else
    set background=dark
endif
" colorscheme solarized       " Uncomment this if you install the solarized plugin
colorscheme everforest

" ============================================================================
" 3. KEY MAPPINGS
" ============================================================================
" Set your leader key (defaults to \, change to space if preferred)
let mapleader = "\\"

" Quick command mode
map ; :

" Split Navigation (Ctrl + h/j/k/l)
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Toggle NERDTree with Ctrl + n
nnoremap <C-n> :NERDTreeToggle<CR>

" Spell Checking Shortcuts
nnoremap <leader>ss :setlocal spell!<CR>
nnoremap <leader>sn ]s
nnoremap <leader>sp [s
nnoremap <leader>sa zg
nnoremap <leader>s? z=

" ============================================================================
" 4. PLUGIN-SPECIFIC CONFIGURATIONS
" ============================================================================

" --- FZF Config ---
" Map Ctrl+P to search for files in the current directory
nnoremap <C-p> :Files<CR>
" Map Leader+b to search through open buffers
nnoremap <leader>b :Buffers<CR>

" --- IndentLine Config ---
let g:indentLine_char = '|'
" Changed from <C-i> because Ctrl+I overrides the Tab key behavior in Vim
nnoremap <leader>i :IndentLinesToggle<CR>

" --- Emmet Config ---
let g:user_emmet_mode = 'a'  " Enable Emmet functions in all modes

" --- Floaterm Configuration ---
" Toggle the terminal with Ctrl + t (in both normal and terminal modes)
nnoremap <C-t> :FloatermToggle<CR>
tnoremap <C-t> <C-\><C-n>:FloatermToggle<CR>

" Optional: Customize the terminal look
let g:floaterm_width = 0.8
let g:floaterm_height = 0.8
let g:floaterm_title = ' Terminal: $1/$2 '
